Photo and Services tab
AlexStoskyi/RentzilaProject pull request #4
Opened 2024-10-23 09:34 UTC by AlexStoskyi

2024-10-23 15:06 UTC, AndreyCar requested changes

2024-10-23 15:06 UTC, AndreyCar commented on tests/PhotoTab/TC_409_VerifyServiceInputSection.spec.ts
I ran this test and got an error 
![image](https://github.com/user-attachments/assets/6b5a718a-d147-4764-b917-4cb30625665a)

2024-10-23 15:06 UTC, AndreyCar commented on tests/PhotoTab/TC_594_VerifyMovingUploadedImage.spec.ts
I ran this test and got an error
![image](https://github.com/user-attachments/assets/6984296b-d81c-4267-bbf0-fccb27a6666c)

2024-10-23 15:06 UTC, AndreyCar commented on tests/PhotoTab/TC_390_VerifyBackButton.spec.ts
> +  const loginPopUpPage = new LoginPopUpPage(page);
Replace it with fixtures

2024-10-23 15:54 UTC, AlexStoskyi commented on tests/PhotoTab/TC_409_VerifyServiceInputSection.spec.ts
<img width="1049" alt="Screenshot 2024-10-23 at 17 53 29" src="https://github.com/user-attachments/assets/d717b268-90e7-461d-8c7a-0d89e1ae5cb5">
дивно у мене інший тест впав))

2024-10-25 11:50 UTC, AndreyCar commented on tests/PhotoTab/TC_409_VerifyServiceInputSection.spec.ts
@AlexStoskyi add the following to the playwright config
```ts
 expect: { timeout: 10_000 },
 use: {
    screenshot: 'only-on-failure',
    video: process.env.CI ? 'on-first-retry' : 'on',
    trace: 'on-first-retry',
  },
```

2024-10-29 16:04 UTC, AndreyCar approved these changes

2024-10-29 16:05 UTC, merged